name: CI
on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      devRelease:
        description: "Is this a dev release?"
        required: true
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Create dev release
        if: ${{ inputs.devRelease }}
        run: |
          echo "Dev release"
        
      # This is because releases _need_ a tag. 
      # Please consider changing the tag later by pushing one.
      - name: Create production release for manual run
        if: ${{ !inputs.devRelease }} && ${{ github.ref_type == "branch" }}
        run: |
          echo "Production release with no tag"

      - name: Create production release with a tag
        if: ${{ !inputs.devRelease }} && contains(github.ref_type, 'tag')
        run: |
          echo "Production release with tag"
