name: Build FLINT AppImage
on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - name: Clone and run the AppImage script
        run: |
          git clone https://github.com/Crystalsage/FLINT-AppImage-Arch.git
          cd FLINT-AppImage-Arch
          git checkout check-ci-build
          chmod +x ./AppImage_FLINT_Build.sh
          ./AppImage_FLINT_Build.sh
          mv /home/runner/tmp/FLINT/Source/build/FLINT-*.AppImage /home/runner/FLINT-${{ matrix.os }}.AppImage


      - name: Create release
        uses: ncipollo/release-action@v1
        with: 
          allowUpdates: true
          tag: release
          prerelease: False
          artifacts: "/home/runner/FLINT-*.AppImage"
          token: ${{ secrets.GITHUB_TOKEN }}
