name: Build FLINT AppImage
on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - name: Clone and run the AppImage script
        run: |
          git clone https://github.com/Crystalsage/FLINT-AppImage-Arch.git
          cd FLINT-AppImage-Arch
          git checkout check-ci-build
          chmod +x ./AppImage_FLINT_Build.sh
          ./AppImage_FLINT_Build.sh
          mv /home/runner/tmp/FLINT/Source/build/FLINT-*.AppImage /home/runner/FLINT-${{ matrix.os }}.AppImage

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-appimage
          path: /home/runner/FLINT-${{ matrix.os }}.AppImage


  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/cache@v3
        with:
          path: /home/runner/FLINT-${{ matrix.os }}.AppImage
          key: ${{ matrix.os }}-appimage
          
      - name: Test AppImages
        run: |
          ls /home/runner/
          ls .
          pwd
          test -f "/home/runner/FLINT-{{ matrix.os }}.AppImage"; echo $?
          echo "All AppImages have been built successfully."

          /home/runner/FLINT-{{ matrix.os }}.AppImage --appimage-extract
          cd squashfs-root
          wget "https://raw.githubusercontent.com/Crystalsage/github-releases-tests/main/test-appimages.sh"
          chmod +x test-appimages.sh
          ./test-appimages.sh


  release:
    needs: [build, test]
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "${{ matrix.os }}-appimage"
          path: /home/runner/FLINT-${{ matrix.os }}.AppImage

      - name: Create release
        uses: ncipollo/release-action@v1
        with: 
          allowUpdates: true
          bodyfile: .github/release.md
          prerelease: False
          artifacts: "/home/runner/FLINT-*.AppImage"
          token: ${{ secrets.GITHUB_TOKEN }}
