name: Build FLINT AppImage
on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master

      - name: Clone and run the AppImage script
        run: |
          touch /home/runner/tmp.txt


      - name: Create release
        uses: ncipollo/release-action@v1
        with: 
          allowUpdates: true
          tag: release
          bodyfile: body.md
          prerelease: False
          artifacts: "/home/runner/tmp.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
