name: Build FLINT AppImage
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Test AppImages
        run: |
          wget -q "https://github.com/Crystalsage/github-releases-tests/releases/download/v9.0/FLINT-${{ matrix.os }}.AppImage"

          test -f FLINT-${{ matrix.os }}.AppImage; echo $?
          echo "All AppImages have been built successfully."

          chmod +x FLINT-${{ matrix.os }}.AppImage
          ./FLINT-${{ matrix.os }}.AppImage --appimage-extract

          cd squashfs-root
          wget "https://raw.githubusercontent.com/Crystalsage/github-releases-tests/main/test-appimages.sh"
          chmod +x test-appimages.sh
          ./test-appimages.sh
