name: Build FLINT AppImage
on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      devRelease:
        description: "Is this a dev release?"
        required: true
        type: boolean

jobs:
  build:
    steps:
      - name: Result
        run: |
          echo "${{ inputs.devRelease }}"
      - name: Release dev
        if: ${{ inputs.devRelease }}
        run: |
          echo "This is a dev release"
      - name: Release normal
        if: ${{ !inputs.devRelease }}
        run: |
          echo "This is a dev release"

